[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "(js|javascript)"
language-id = "javascript"
file-types = ["js", "mjs", "cjs", "rules", "es6", "pac", { glob = ".node_repl_history" }, { glob = "jakefile" }]
shebangs = ["deno"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "deno-lsp" ]
indent = { tab-width = 2, unit = "  " }

# [language.debugger]
# name = "node-debug2"
# transport = "stdio"
# # args consisting of cmd (node) and path to adapter should be added to user's configuration
# quirks = { absolute-paths = true }

# [[language.debugger.templates]]
# name = "source"
# request = "launch"
# completion = [ { name = "main", completion = "filename", default = "index.js" } ]
# args = { program = "{0}" }

[[grammar]]
name = "javascript"
source = { git = "https://github.com/tree-sitter/tree-sitter-javascript", rev = "f772967f7b7bc7c28f845be2420a38472b16a8ee" }

[[language]]
name = "jsx"
scope = "source.jsx"
injection-regex = "jsx"
language-id = "javascriptreact"
file-types = ["jsx"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "typescript-language-server" ]
indent = { tab-width = 2, unit = "  " }
grammar = "javascript"

[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
formatter = {command = "deno", args=["fmt","-","--ext","ts"]}
auto-format = true
indent = { tab-width = 2, unit = "  " }
language-servers = ["deno-lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[language-server.deno-lsp.config.deno]
enable = true

